# Generated by Django 5.2.3 on 2025-06-13 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='symbol')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='factor')),
                ('date', models.DateField(verbose_name='date')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversionrates_from', to='currencies.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversionrates_to', to='currencies.currency')),
            ],
            options={
                'verbose_name': 'conversion rate',
                'verbose_name_plural': 'conversion rates',
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
    ]
