# Generated by Django 5.2.3 on 2025-06-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_base_currency',
            field=models.BooleanField(default=False, verbose_name='base currency'),
        ),
        migrations.AlterUniqueTogether(
            name='conversionrate',
            unique_together={('from_currency', 'to_currency', 'date')},
        ),
    ]
