# Generated by Django 5.2.3 on 2025-06-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_currency_is_base_currency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversionrate',
            unique_together=set(),
        ),
    ]
