# Generated by Django 5.2.3 on 2025-06-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_alter_conversionrate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversionrate',
            unique_together={('from_currency', 'to_currency', 'date')},
        ),
    ]
