# Generated by Django 5.2.3 on 2025-06-15 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_alter_conversionrate_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='factor')),
                ('date', models.DateField(verbose_name='date')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversionfactors_from', to='currencies.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversionfactors_to', to='currencies.currency')),
            ],
            options={
                'verbose_name': 'conversion rate',
                'verbose_name_plural': 'conversion rates',
                'ordering': ['-date'],
                'get_latest_by': 'date',
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='ConversionRate',
        ),
    ]
