# Generated by Django 5.2.3 on 2025-06-15 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0005_conversionfactor_delete_conversionrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversionfactor",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="date"
            ),
        ),
    ]
